services:
  - type: web
    name: new-stranger-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: AGORA_APP_ID
        value: 8fad472fea6c40dcaf4bd00b394ad814
      - key: AGORA_APP_CERTIFICATE
        value: beb9712340434846a6c9f3e5d0a5c7e0
